### ISSUE TITLE
i think the code cant close the pop up window after a video has been posted

### ISSUE THREAD

**Issue by bryanseah234** [Niedzwiedzw/youtube-publish-drafts#1]
VM398:49 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at waitForElement (<anonymous>:49:34)
    at SuccessDialog.closeDialogButton (<anonymous>:97:26)
    at SuccessDialog.close (<anonymous>:101:30)
    at Object.publishDrafts [as publish_drafts] (<anonymous>:227:26)

^^ this is the error throw back in the developer console

![image](https://user-images.githubusercontent.com/66017805/110189699-dfb0e280-7e5a-11eb-8464-8b78c1362f0e.png)

**Comment by Weelnar** [comment]
Same problem
The issue: 
Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at waitForElement (<anonymous>:52:34)
    at SuccessDialog.closeDialogButton (<anonymous>:77:26)
    at SuccessDialog.close (<anonymous>:81:30)
    at main (<anonymous>:205:26)
waitForElement @ VM4449:52
closeDialogButton @ VM4449:77
close @ VM4449:81
main @ VM4449:205
async function (async)
main @ VM4449:194
(anonymous) @ VM4449:210
(anonymous) @ VM4449:211

**Comment by bryanseah234** [comment]
i have a suspircion that the issue lies with the getElementbyId for the close button. it is current "iron-icon".. can't seem to find a better Id to call the close button.. zzz

**Comment by teatime-dev** [comment]
changing 
`const DIALOG_SELECTOR = 'ytcp-dialog.ytcp-video-share-dialog > paper-dialog:nth-child(1)';`
to
`const DIALOG_SELECTOR = 'ytcp-dialog.ytcp-video-share-dialog > tp-yt-paper-dialog:nth-child(1)';`
seems to fix it for me

**Comment by bryanseah234** [comment]
sad. youtube introduced 'checks' and now the code doesnt work at all

**Comment by Weelnar** [comment]
> sad. youtube introduced 'checks' and now the code doesnt work at all

Yea, pls fix it guys :))

**Comment by Weelnar** [comment]
guys, I need your help.  Is it possible to modify this script so that instead of making all the videos available, each video is sent for a different hour in postponed publication, it is desirable that this can be configured, for example, the script is launched, the first video is sent on March 21 at 10 am, the next 11 am, and so on  Further.  Well, of course, the problem with YouTube checks needs to be solved, I would be very grateful and in the future I would thank

**Comment by asdsadsaasd12312132** [comment]
You have to do it semi-manually now. Steps:

1. run javascript
2. close the prompt
3. repeat

**Comment by Weelnar** [comment]
> You have to do it semi-manually now. Steps:
> 
> 1. run javascript
> 2. close the prompt
> 3. repeat

It has no sence in this way, that's the same that we can do w/o any script step by step make each video public

**Comment by asdsadsaasd12312132** [comment]
> > You have to do it semi-manually now. Steps:
> > 
> > 1. run javascript
> > 2. close the prompt
> > 3. repeat
> 
> It has no sence in this way, that's the same that we can do w/o any script step by step make each video public

That is why I said semi-manual. Anyway, since the process is repetitive, it is possible to fully automate it by using AHK.

**Comment by damianwest** [comment]
I got it working but I don't know how to leave a comment on the code.

I removed " > paper-dialog:nth-child(1)" and changed "iron-icon" to "tp-yt-iron-icon"

Not sure if the 2nd change is necessary but it's working.

**Comment by teatime-dev** [comment]
> 
> 
> I got it working but I don't know how to leave a comment on the code.
> 
> I removed " > paper-dialog:nth-child(1)" and changed "iron-icon" to "tp-yt-iron-icon"
> 
> Not sure if the 2nd change is necessary but it's working.

i submitted a pull request with this fix about 2 weeks ago and it hasnt gone through yet unfortunately

**Comment by reisher** [comment]
> > I got it working but I don't know how to leave a comment on the code.
> > I removed " > paper-dialog:nth-child(1)" and changed "iron-icon" to "tp-yt-iron-icon"
> > Not sure if the 2nd change is necessary but it's working.
> 
> i submitted a pull request with this fix about 2 weeks ago and it hasnt gone through yet unfortunately

because it does not fix it

**Comment by teatime-dev** [comment]
> 
> 
> > > I got it working but I don't know how to leave a comment on the code.
> > > I removed " > paper-dialog:nth-child(1)" and changed "iron-icon" to "tp-yt-iron-icon"
> > > Not sure if the 2nd change is necessary but it's working.
> > 
> > 
> > i submitted a pull request with this fix about 2 weeks ago and it hasnt gone through yet unfortunately
> 
> because it does not fix it

it did work when I submitted it, however it appears that they've changed it yet again, breaking it. I'll see if i can fix it. i reckon they'll change it again though in a few days as it seems to be...

**Comment by teatime-dev** [comment]
@reisher 
I've hopefully fixed it. would you kindly test for me (before youtube messes with it again)?
#2

**Comment by reisher** [comment]
> @reisher
> I've hopefully fixed it. would you kindly test for me (before youtube messes with it again)?
> #2

It works now but only for one video as soon as it finishes the window is closed but it won't proceed to the next video

**Comment by asdsadsaasd12312132** [comment]
> > @reisher
> > I've hopefully fixed it. would you kindly test for me (before youtube messes with it again)?
> > #2
> 
> It works now but only for one video as soon as it finishes the window is closed but it won't proceed to the next video

It works perfectly for me i.e. everything is fully automated.

**Comment by teatime-dev** [comment]
> 
> 
> > > > @reisher
> > > > I've hopefully fixed it. would you kindly test for me (before youtube messes with it again)?
> > > > #2
> > > 
> > > 
> > > It works now but only for one video as soon as it finishes the window is closed but it won't proceed to the next video
> > 
> > 
> > It works perfectly for me i.e. everything is fully automated.
> 
> Even if it works, how many video can you upload to yt without delayed publication before it will get shadowban and zero views for them?)
> I tried to upload about 30~50 video by this way but everytime it's getting shadowban)
> 
> However, if those videos published with delayed piblication, even every 15-30min or a hour, it works good ans getting views)
> 
> That's why i requested
> 
> > guys, I need your help. Is it possible to modify this script so that instead of making all the videos public, each video is sent for a different hour in postponed publication, it is desirable that this can be configured, for example, the script is launched, the first video is sent on March 21 at 10 am, the next 11 am, and so on Further. Well, of course, the problem with YouTube checks needs to be solved, I would be very grateful and in the future I would thank

Personally, this isn't an issue for me as I only use this for unlisted videos, and it is also be beyond my javascript abilities but that's beside the point. I would recommend you open another issue for this as a suggestion, since this is just about the bugs introduced with youtube changing their HTML :) Hopefully the owner can give you some advice then.

**Comment by Weelnar** [comment]
> > Even if it works, how many video can you upload to yt without delayed publication before it will get shadowban and zero views for them?)
> > I tried to upload about 30~50 video by this way but everytime it's getting shadowban)
> > However, if those videos published with delayed piblication, even every 15-30min or a hour, it works good ans getting views)
> > That's why i requested
> > > guys, I need your help. Is it possible to modify this script so that instead of making all the videos public, each video is sent for a different hour in postponed publication, it is desirable that this can be configured, for example, the script is launched, the first video is sent on March 21 at 10 am, the next 11 am, and so on Further. Well, of course, the problem with YouTube checks needs to be solved, I would be very grateful and in the future I would thank
> 
> Personally, this isn't an issue for me as I only use this for unlisted videos, and it is also be beyond my javascript abilities but that's beside the point. I would recommend you open another issue for this as a suggestion, since this is just about the bugs introduced with youtube changing their HTML :) Hopefully the owner can give you some advice then.
Ok, sorry for the flood, but...
1.What's the reason to upload unlisted videos?))
2. I guess the "promises" in javascript would get this point with delayed publications))

**Comment by teatime-dev** [comment]
> 
> Ok, sorry for the flood, but...
> 1.What's the reason to upload unlisted videos?))
> 2. I guess the "promises" in javascript would get this point with delayed publications))

1. I just use it for playing music through a discord bot. It's unlisted as I don't want actual people to watch it and report for copyright etc. So i have plenty of songs that i need to publish in bulk unlisted that this script helps with😃 
2. That might be a solution. However, as said before my javascript skills are only enough to fix bugs like this so I can't say if that would work

Again, I would recommend you open another issue on the repository so you can suggest the feature you want as this issue is just about a bug and not a suggestion.

**Comment by asdsadsaasd12312132** [comment]
> > > Even if it works, how many video can you upload to yt without delayed publication before it will get shadowban and zero views for them?)
> > > I tried to upload about 30~50 video by this way but everytime it's getting shadowban)
> > > However, if those videos published with delayed piblication, even every 15-30min or a hour, it works good ans getting views)
> > > That's why i requested
> > > > guys, I need your help. Is it possible to modify this script so that instead of making all the videos public, each video is sent for a different hour in postponed publication, it is desirable that this can be configured, for example, the script is launched, the first video is sent on March 21 at 10 am, the next 11 am, and so on Further. Well, of course, the problem with YouTube checks needs to be solved, I would be very grateful and in the future I would thank
> > 
> > 
> > Personally, this isn't an issue for me as I only use this for unlisted videos, and it is also be beyond my javascript abilities but that's beside the point. I would recommend you open another issue for this as a suggestion, since this is just about the bugs introduced with youtube changing their HTML :) Hopefully the owner can give you some advice then.
> 
> Ok, sorry for the flood, but...
> 1.What's the reason to upload unlisted videos?))
> 2. I guess the "promises" in javascript would get this point with delayed publications))

Stop derailing the thread. Nobody cares.

**Comment by Niedzwiedzw** [comment]
sorry guys, didn't notice the discussion, I will look into it on saturday, promise!
