### ISSUE TITLE
Just works on first time, so I have to paste the code again and over...

### ISSUE THREAD

**Issue by LuisSpader** [Niedzwiedzw/youtube-publish-drafts#12]
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at waitForElement (<anonymous>:69:34)
    at SuccessDialog.closeDialogButton (<anonymous>:117:26)
    at SuccessDialog.close (<anonymous>:121:30)
    at Object.publishDrafts [as publish_drafts] (<anonymous>:247:26)
waitForElement @ VM301:69
closeDialogButton @ VM301:117
close @ VM301:121
publishDrafts @ VM301:247

**Comment by mitchlin71** [comment]
I got this to somehow work for publishing video's by making the following changes:

at line 102:
`//	const MADE_FOR_KIDS_SELECTOR = '#made-for-kids-group';`
`	const VIDEO_MADE_FOR_KIDS_NOT_MFK = '#made-for-kids-group';`

at line 248:
`//     await dialog.close();`

Note: that once it closes the draft screen, it takes approx 10 secs to automatically open the next screen
